### ISSUE TITLE
汉字识别

### ISSUE THREAD

**Issue by ukaiyuan** [czczup/Captcha-Recognition#4]
![TIM图片20200706155048](https://user-images.githubusercontent.com/28975105/86569279-be80b500-bfa0-11ea-9d7f-01a2be232e02.png)

像这样验证码,需要在4组选项,每组4个汉字中,选择一组匹配的汉字.
应该经过哪些步骤的处理?

**Comment by czczup** [comment]
> ![TIM图片20200706155048](https://user-images.githubusercontent.com/28975105/86569279-be80b500-bfa0-11ea-9d7f-01a2be232e02.png)
> 
> 像这样验证码,需要在4组选项,每组4个汉字中,选择一组匹配的汉字.
> 应该经过哪些步骤的处理?

有点没明白，是给1张图，上面有四个汉字，然后再给四组汉字，从中选一组匹配的吗？

**Comment by wangxiaoran1995** [comment]
level2的例子中，我想用ckpt文件生成pb模型，但是需要指定输出名字。我是用ArgMax显示不存在。 使用FC2/wx_plus_b结果好像对不上。
